#!/bin/sh

set -e

case "$1" in
    purge|remove)
        if [ -n "$(grep "/var/lib/rkt" /proc/mounts)" ]; then
            printf "rkt/prerm error: detected active mounts in [/var/lib/rkt].\n"
            exit 1
        fi
        if [ -n "$(rkt list --no-legend | awk '{print $4}' | grep running)" ]; then
            printf "rkt/prerm error: detected running containers.\n"
            exit 1
        fi
    ;;
esac

#DEBHELPER#
